services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    env_file:
      - .env
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
    depends_on:
      - mongodb
    
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    