export enum Language {
    Afrikaans = 'af',
    Albanian = 'sq',
    Amharic = 'am',
    Arabic = 'ar',
    Armenian = 'hy',
    Azerbaijani = 'az',
    Basque = 'eu',
    Belarusian = 'be',
    Bengali = 'bn',
    Bosnian = 'bs',
    Bulgarian = 'bg',
    Catalan = 'ca',
    Cebuano = 'ceb',
    Chichewa = 'ny',
    ChineseSimplified = 'zh-cn',
    ChineseTraditional = 'zh-tw',
    Corsican = 'co',
    Croatian = 'hr',
    Czech = 'cs',
    Danish = 'da',
    Dutch = 'nl',
    English = 'en',
    Esperanto = 'eo',
    Estonian = 'et',
    Filipino = 'tl',
    Finnish = 'fi',
    French = 'fr',
    Frisian = 'fy',
    Galician = 'gl',
    Georgian = 'ka',
    German = 'de',
    Greek = 'el',
    Gujarati = 'gu',
    HaitianCreole = 'ht',
    Hausa = 'ha',
    Hawaiian = 'haw',
    Hebrew = 'iw',
    Hindi = 'hi',
    Hmong = 'hmn',
    Hungarian = 'hu',
    Icelandic = 'is',
    Igbo = 'ig',
    Indonesian = 'id',
    Irish = 'ga',
    Italian = 'it',
    Japanese = 'ja',
    Javanese = 'jw',
    Kannada = 'kn',
    Kazakh = 'kk',
    Khmer = 'km',
    Korean = 'ko',
    KurdishKurmanji = 'ku',
    Kyrgyz = 'ky',
    Lao = 'lo',
    Latin = 'la',
    Latvian = 'lv',
    Lithuanian = 'lt',
    Luxembourgish = 'lb',
    Macedonian = 'mk',
    Malagasy = 'mg',
    Malay = 'ms',
    Malayalam = 'ml',
    Maltese = 'mt',
    Maori = 'mi',
    Marathi = 'mr',
    Mongolian = 'mn',
    MyanmarBurmese = 'my',
    Nepali = 'ne',
    Norwegian = 'no',
    Odia = 'or',
    Pashto = 'ps',
    Persian = 'fa',
    Polish = 'pl',
    Portuguese = 'pt',
    Punjabi = 'pa',
    Romanian = 'ro',
    Russian = 'ru',
    Samoan = 'sm',
    ScotsGaelic = 'gd',
    Serbian = 'sr',
    Sesotho = 'st',
    Shona = 'sn',
    Sindhi = 'sd',
    Sinhala = 'si',
    Slovak = 'sk',
    Slovenian = 'sl',
    Somali = 'so',
    Spanish = 'es',
    Sundanese = 'su',
    Swahili = 'sw',
    Swedish = 'sv',
    Tajik = 'tg',
    Tamil = 'ta',
    Telugu = 'te',
    Thai = 'th',
    Turkish = 'tr',
    Ukrainian = 'uk',
    Urdu = 'ur',
    Uyghur = 'ug',
    Uzbek = 'uz',
    Vietnamese = 'vi',
    Welsh = 'cy',
    Xhosa = 'xh',
    Yiddish = 'yi',
    Yoruba = 'yo',
    Zulu = 'zu',
}
  
  // Create a mapping of language codes to display names
export const LanguageNames: { [key in Language]: string } = {
    [Language.Afrikaans]: 'Afrikaans',
    [Language.Albanian]: 'Albanian',
    [Language.Amharic]: 'Amharic',
    [Language.Arabic]: 'Arabic',
    [Language.Armenian]: 'Armenian',
    [Language.Azerbaijani]: 'Azerbaijani',
    [Language.Basque]: 'Basque',
    [Language.Belarusian]: 'Belarusian',
    [Language.Bengali]: 'Bengali',
    [Language.Bosnian]: 'Bosnian',
    [Language.Bulgarian]: 'Bulgarian',
    [Language.Catalan]: 'Catalan',
    [Language.Cebuano]: 'Cebuano',
    [Language.Chichewa]: 'Chichewa',
    [Language.ChineseSimplified]: 'Chinese (Simplified)',
    [Language.ChineseTraditional]: 'Chinese (Traditional)',
    [Language.Corsican]: 'Corsican',
    [Language.Croatian]: 'Croatian',
    [Language.Czech]: 'Czech',
    [Language.Danish]: 'Danish',
    [Language.Dutch]: 'Dutch',
    [Language.English]: 'English',
    [Language.Esperanto]: 'Esperanto',
    [Language.Estonian]: 'Estonian',
    [Language.Filipino]: 'Filipino',
    [Language.Finnish]: 'Finnish',
    [Language.French]: 'French',
    [Language.Frisian]: 'Frisian',
    [Language.Galician]: 'Galician',
    [Language.Georgian]: 'Georgian',
    [Language.German]: 'German',
    [Language.Greek]: 'Greek',
    [Language.Gujarati]: 'Gujarati',
    [Language.HaitianCreole]: 'Haitian Creole',
    [Language.Hausa]: 'Hausa',
    [Language.Hawaiian]: 'Hawaiian',
    [Language.Hebrew]: 'Hebrew',
    [Language.Hindi]: 'Hindi',
    [Language.Hmong]: 'Hmong',
    [Language.Hungarian]: 'Hungarian',
    [Language.Icelandic]: 'Icelandic',
    [Language.Igbo]: 'Igbo',
    [Language.Indonesian]: 'Indonesian',
    [Language.Irish]: 'Irish',
    [Language.Italian]: 'Italian',
    [Language.Japanese]: 'Japanese',
    [Language.Javanese]: 'Javanese',
    [Language.Kannada]: 'Kannada',
    [Language.Kazakh]: 'Kazakh',
    [Language.Khmer]: 'Khmer',
    [Language.Korean]: 'Korean',
    [Language.KurdishKurmanji]: 'Kurdish (Kurmanji)',
    [Language.Kyrgyz]: 'Kyrgyz',
    [Language.Lao]: 'Lao',
    [Language.Latin]: 'Latin',
    [Language.Latvian]: 'Latvian',
    [Language.Lithuanian]: 'Lithuanian',
    [Language.Luxembourgish]: 'Luxembourgish',
    [Language.Macedonian]: 'Macedonian',
    [Language.Malagasy]: 'Malagasy',
    [Language.Malay]: 'Malay',
    [Language.Malayalam]: 'Malayalam',
    [Language.Maltese]: 'Maltese',
    [Language.Maori]: 'Maori',
    [Language.Marathi]: 'Marathi',
    [Language.Mongolian]: 'Mongolian',
    [Language.MyanmarBurmese]: 'Myanmar (Burmese)',
    [Language.Nepali]: 'Nepali',
    [Language.Norwegian]: 'Norwegian',
    [Language.Odia]: 'Odia',
    [Language.Pashto]: 'Pashto',
    [Language.Persian]: 'Persian',
    [Language.Polish]: 'Polish',
    [Language.Portuguese]: 'Portuguese',
    [Language.Punjabi]: 'Punjabi',
    [Language.Romanian]: 'Romanian',
    [Language.Russian]: 'Russian',
    [Language.Samoan]: 'Samoan',
    [Language.ScotsGaelic]: 'Scots Gaelic',
    [Language.Serbian]: 'Serbian',
    [Language.Sesotho]: 'Sesotho',
    [Language.Shona]: 'Shona',
    [Language.Sindhi]: 'Sindhi',
    [Language.Sinhala]: 'Sinhala',
    [Language.Slovak]: 'Slovak',
    [Language.Slovenian]: 'Slovenian',
    [Language.Somali]: 'Somali',
    [Language.Spanish]: 'Spanish',
    [Language.Sundanese]: 'Sundanese',
    [Language.Swahili]: 'Swahili',
    [Language.Swedish]: 'Swedish',
    [Language.Tajik]: 'Tajik',
    [Language.Tamil]: 'Tamil',
    [Language.Telugu]: 'Telugu',
    [Language.Thai]: 'Thai',
    [Language.Turkish]: 'Turkish',
    [Language.Ukrainian]: 'Ukrainian',
    [Language.Urdu]: 'Urdu',
    [Language.Uyghur]: 'Uyghur',
    [Language.Uzbek]: 'Uzbek',
    [Language.Vietnamese]: 'Vietnamese',
    [Language.Welsh]: 'Welsh',
    [Language.Xhosa]: 'Xhosa',
    [Language.Yiddish]: 'Yiddish',
    [Language.Yoruba]: 'Yoruba',
    [Language.Zulu]: 'Zulu',
    // Add more language names as needed
  };